### PR TITLE
Update to v0.12.1

### PR DESCRIPTION
**Pull request by oblute**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oblute** [comment]
@conda-forge-admin, please rerender

**Comment by oblute** [comment]
@andrewmchen @jaroslawk can you merge this? i'm also happy to be a maintainer if you need help with the feedstock. thanks!

**Comment by oblute** [comment]
@conda-forge/core would it be possible to get this merged? i pinged the maintainers awhile ago but still waiting

**Comment by xhochy** [comment]
@oblute Do you want to add yourself as a maintainer here?

**Pull request merged**
